###WARNING THIS FILE IS SET TO NOT BE REPLACED IF EXISTS ON SERVER ALREADY###
###DELETE THIS FILE BEFORE MAKING CHANGES TO NON AUTOGENERATED SECTIONS###

export JAVA_HOME=`echo $JRE_HOME`
### START :: SALT :: set_java_opts Generated Automatically DO NOT EDIT!!###


### END :: SALT :: set_java_opts Generated Automatically DO NOT EDIT!!###

### START :: SALT :: set_java_mem Generated Automatically DO NOT EDIT!!###


### END :: SALT :: set_java_mem Generated Automatically DO NOT EDIT!!###

### START :: SALT :: configure_build_env Generated Automatically DO NOT EDIT!!###


### END :: SALT :: configure_build_env Generated Automatically DO NOT EDIT!!###

export PATH=$JAVA_HOME/bin:$PATH
TOMCAT_HOME=`echo $TOMCAT_HOME`
